### ISSUE TITLE
Error with data transmission to Feinstaub-App server

### ISSUE THREAD

**Issue by mrgames13** [opendata-stuttgart/sensors-software#537]
In the latest beta version there is a bug with the data transmission to the Feinstaub-App server (h2801469.stratoserver.net). Were there changings, which could lead to that error?

I hope we can manage this issue until the version goes stable and will be distributed to all users. We already receive one email every minute.

Thanks in advance!

**Comment by dirkmueller** [comment]
It is possible that there were changes.. which error do you have?

**Comment by mrgames13** [comment]
All we know is, that version NRZ-2019-125-B1 worked well and since then, our server does not receive data any more. From no sensor that has been updated to one of the next versions. So we assume, that there changed something, when sending the data to our server.

**Comment by dirkmueller** [comment]
I think I found something..

**Comment by dirkmueller** [comment]
Should be fixed by the PR above.

**Comment by mrgames13** [comment]
Great! Thanks a lot. Only the release of the update is missing ;)

**Comment by ricki-z** [comment]
If I read the changes, it should also work if there were a 2048 bit certificate for https at the FsApp server (larger certs will cause a memory overflow).

**Comment by mrgames13** [comment]
That's right. Should also work on port 443. Maybe the port change does not fix the problem described above?!

**Comment by ricki-z** [comment]
I have checked the master branch source code. There is a forced unencrypted connection used for the FsApp.
I will push a new beta (will have the same number, but should update on sensor restart).
Could you please test this with that version?

**Comment by mrgames13** [comment]
No, that does not work.

**Comment by ricki-z** [comment]
Did you switch to beta?

**Comment by mrgames13** [comment]
Sure

**Comment by ricki-z** [comment]
The transmission to the FsApp server is using the same format we use to transmit data to Madavi.de. And there it's working ...
Can you see any error messages on your server?

**Comment by mrgames13** [comment]
I checked the server logs. There is no single request for today, which does not have the result code 200. It seems so, if the requests would not reach the server.
I recognized a strange thing. It seems, that one single sensor located in Malaysia / George Town is able to send its data with firmware NRZ-2019-126-B3. The server log contains several occurences of this line:

[04/Nov/2019:00:29:18 +0000] "POST /data.php HTTP/1.1" 200 261 "-" "NRZ-2019-126-B3/393834"

**Comment by mrgames13** [comment]
I've tested around a bit and I tried to enter the server host, path and port into the corresponding fields for the custom API endpoint. Following configurations worked:

Host: h2801469.stratoserver.net (with or without www. at the beginning)
Path: /data.php
Port: 443 (HTTPS option above enabled)

And

Host: h2801469.stratoserver.net (with or without www. at the beginning)
Path: /data.php
Port: 80 (HTTPS disabled)

**Comment by dirkmueller** [comment]
it does work for my two sensors with the patch. the issue before was that it sent *unencrypted* http to port 443, which just produces garbage and is being rejected. Now it sends to port 80 unencrypted http, which is the same state like the stable firmware and it seems to work. I can see data submissions of my beta sensor in the app that are current.

**Comment by mrgames13** [comment]
Okay. I tested it again and it works now. Thank you for your help!
@ricki-z maybe you can include the https support as we have agreed per mail.

**Comment by mrgames13** [comment]
Hi again,
I have to reopen the issue, cause the bug appeared again. Since version NRZ-126-B4 the data gets lost on its way again. As I mentioned, if you configure the optional API like that:

> Host: h2801469.stratoserver.net (with or without www. at the beginning)
> Path: /data.php
> Port: 443 (HTTPS option above enabled)
> 
> Or
> 
> Host: h2801469.stratoserver.net (with or without www. at the beginning)
> Path: /data.php
> Port: 80 (HTTPS disabled)

it works like a charm.

Looking forward to your answer!

**Comment by dirkmueller** [comment]
Confirmed. Weird. I thought I properly tested this.

What changed is that I enabled tls. And likely the server does not support 'Maximum Fragment Length Negotiation' which we require because it reduces memory pressure and works for all the other predefined APIs

**Comment by dirkmueller** [comment]
actually using openssl s_client -connect h2801469.stratoserver.net:443  gives

```
    Start Time: 1573226278
    Timeout   : 7200 (sec)
    Verify return code: 10 (certificate has expired)
```

for me. we have TLS verification turned on. I verified that turning off verification makes it succeed sending data again.

**Comment by mrgames13** [comment]
Thanks for the fix. @ricki-z Could we merge this into beta?

**Comment by ricki-z** [comment]
Is merged in beta and uploaded to the update server.

**Comment by mrgames13** [comment]
Thanks! I tested it and it seems to work? It takes 24 hours until all beta users have this update, right?

**Comment by ricki-z** [comment]
Yes, the sensors should update in 24 hours. But they will also update after a restart.

**Comment by mrgames13** [comment]
Awesome. Thanks for the fix!
